<a href="https://colab.research.google.com/github/silviutroscot/Machine-Learning-Playground/blob/master/Pytorch101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# install pytorch and pytorch vision
!pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
!pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

In [0]:
import torch
import torchvision

In [0]:
# sigmoid activation function of input x as torch.Tensor
def sigmoid_activation(x):
    return 1/(1+torch.exp(-x))

In [0]:
# generate random data
torch.manual_seed(7)

# features are 5 random variables; this creates a 1 dimension tensor, with 5 elements
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [26]:
# compute the activation function
res = sigmoid_activation(torch.sum(features * weights) + bias)
mm_res = sigmoid_activation(torch.mm(features, weights.view(5,1)) + bias)
print (res)
print (mm_res)

tensor([[0.1595]])
tensor([[0.1595]])


In [0]:
# generate input and weights for a multi layer NN
# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [44]:
# compute the values of the 2 neurons in the first layer
first_layer = torch.mm(features, W1) + B1
first_layer_activation = sigmoid_activation(first_layer)
print (first_layer_activation)
# compute the output of the NN
res = sigmoid_activation(torch.mm(first_layer_activation, W2) + B2)
print(res)

tensor([[0.1613, 0.2716]])
tensor([[0.4923]])
